Repository VKCOM/noverify, pull requests merged in 2022-08, with the labels that each got.

#1187 ir: added parent field for all nodes
  src/ir/codegen/gen_clone.go
  src/ir/codegen/gen_equal.go
  src/ir/codegen/gen_get_first_token.go
  src/ir/codegen/gen_iterate_tokens.go
  src/ir/codegen/gen_parent.go
  src/ir/codegen/gen_walk.go
  src/ir/codegen/main.go
  src/ir/get_first_token.go
  src/ir/get_parent.go
  src/ir/ir.go
  src/ir/irconv/irconv.go
  src/ir/irutil/clone.go
  src/ir/irutil/equal.go
  src/ir/irutil/find_walker.go
  src/ir/irutil/irtutil.go
  src/ir/irutil/irutil_test.go
  src/ir/node_types.go
  src/ir/utils.go
  src/ir/walk.go
  src/linter/root.go
  src/linter/root_checker.go
  src/phpgrep/meta_nodes.go
  src/rules/parser.go
Labels: enhancement

#1167 linter: added initial support for `@noverify-suppress` annotations
  src/ir/irconv/utils.go
  src/linter/block.go
  src/linter/block_linter.go
  src/linter/root.go
  src/tests/checkers/linter_suppress_test.go
Labels: enhancement

#1190 updated list of aliases
  src/ir/phpcore/phpcore.go
Labels: refactoring

#1192 added PhpStorm plugins
  README.md
  docs/phpstorm-plugin.md
Labels: documentation
