Repository VKCOM/noverify, pull requests merged in 2024-07, with the labels that each got.

#1222 dynamic rules: `path-exclude` rule fix
  src/rules/parser.go
  src/tests/rules/rules_test.go
Labels: bug, dynamic-rules

#1226 docs: fixed the error generating `GitHub Pages`
  docs/_config.yml
Labels: documentation

#1224 dinamic rules: multiple path
  src/linter/utils.go
  src/rules/parser.go
  src/rules/rules.go
  src/rules/util.go
  src/tests/rules/rules_error_test.go
  src/tests/rules/rules_test.go
Labels: enhancement, dynamic-rules

#1215 linter: fixed unboxing from null for arrays
  src/solver/solver.go
  src/tests/exprtype/exprtype_test.go
  src/types/lazy.go
  src/types/map.go
Labels: bug

#1230 updated `GitHub Action`
  .github/workflows/go.yml
  .github/workflows/linter.yml
  .github/workflows/tests.yml
Labels: refactoring
